class_name Constants

static var PLAYER_COLLISION_MASK = 2

static var COLOUR_PLAYER_PLANNING_DEFAULT = Color.BLACK
static var COLOUR_PLAYER_PLANNING_HOVERED = Color(0.4,0.4,0.4)
static var COLOUR_PLAYER_PLANNING_SELECTED = Color.WHITE
static var COLOUR_PLAYER_PLANNING_RECORDING = Color.KHAKI
